### ISSUE TITLE
Use libnftables directly instead of the nft executable binary

### ISSUE THREAD

**Issue by EdDev** [networkplumbing/go-nft#18]
By using `libnftables` directly, there is no need to exec a new process.
For the user perspective, it should look the same, as the details of how to apply/read the nftables configuration is abstracted away.

For this enhancement, there is a need to create a Go binding to the C library.

**Comment by qinqon** [comment]
let's give it a try, first try it with dynamic library, then we can entertain the idea of linking directly libnmstate.a (in case it exists).
